version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project-planner
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
